version: '3.9'

services:
  cron-job-backup:
    volumes:
      - /logs
      - /backup-files
    build:
      context: .
      args:
        db_to_dump_connection_arg: ${DB_TO_DUMP_CONNECTION}
        db_to_restore_connection_arg: ${DB_TO_RESTORE_CONNECTION}
    deploy:
        restart_policy:
          condition: on-failure
          delay: 5s
          max_attempts: 3

