version: '3.9'

services:
  cron-job-backup:
    volumes:
      - /logs
      - /backup-files

    build: .
    environment:
      - DB_TO_DUMP_CONNECTION=${DB_TO_DUMP_CONNECTION}
      - DB_TO_RESTORE_CONNECTION=${DB_TO_RESTORE_CONNECTION}
    deploy:
        restart_policy:
          condition: on-failure
          delay: 5s
          max_attempts: 3



# to deploy from your machine, create a context:
# docker context create remote --docker "host=ssh://draft@192.168.1.5:22"
# docker --context remote stack deploy -c bitcoin-docker-compose.yml btc
# docker --context remote logs btc_bitcoind.1.*