version: '3.9'

services:
  cron-backup-service:
    image: cron-job-image
    env_file:
      - .env
    volumes:
      - logs:/logs
      - backup-files:/backup-files
    build: .
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3

volumes:
  logs:
  backup-files: